export const ROUTE_PATHS = {
  home: "/",
  aboutUs: "/about-us",
  contactUs: "/contact-us",
  courses: "/courses",
  courseId: ":courseId",
  courseOverview: "/courses/:courseId",
  topics: "/topics",
  topicsOverview: "/topics/:topicId",
  topicId: ":topicId",
  interviewKit: "/interview-kit",
  comingSoon: "/comming-soon",
  training: "/training",
  upcoming: "/upcoming",
  liveProjects :"/live-projects",
  profile:"/profile",
  personalInformation:"/profile/personalInformation",
  resumeMaker:"/resumeMaker",
  viewUserProfile:"/viewUserProfile"
};
